from app.services.db.base_service import BaseDBService
from typing import Dict, List, Any, Optional
import logging

logger = logging.getLogger(__name__)

class ExerciseDefinitionService(BaseDBService):
    """
    Service for handling exercise definition operations in the database
    """
    
    async def get_all_exercise_definitions(self) -> List[Dict[str, Any]]:
        """
        Get all exercise definitions ordered by standard_name
        """
        try:
            logger.info("Fetching all exercise definitions")
            
            result = await self.supabase.db.table("exercise_definitions") \
                .select("*") \
                .order("standard_name", ascending=True) \
                .execute()
                
            if result.error:
                raise Exception(f"Failed to fetch exercise definitions: {result.error.message}")
                
            definitions = result.data or []
            
            logger.info(f"Fetched {len(definitions)} exercise definitions")
            return definitions
            
        except Exception as e:
            logger.error(f"Error getting exercise definitions: {str(e)}")
            return await self.handle_error("get_all_exercise_definitions", e)
    
    async def create_exercise_definition(self, exercise_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Create a new exercise definition
        """
        try:
            logger.info(f"Creating new exercise definition: {exercise_data.get('standard_name')}")
            
            # Remove any fields that should be generated by the database
            if 'id' in exercise_data:
                del exercise_data['id']
            if 'created_at' in exercise_data:
                del exercise_data['created_at']
            if 'updated_at' in exercise_data:
                del exercise_data['updated_at']
            
            result = await self.supabase.db.table("exercise_definitions") \
                .insert(exercise_data) \
                .execute()
                
            if result.error:
                raise Exception(f"Failed to create exercise definition: {result.error.message}")
                
            if not result.data:
                raise Exception("No data returned from insert")
                
            created_definition = result.data[0]
            
            logger.info(f"Exercise definition created with ID: {created_definition.get('id')}")
            return created_definition
            
        except Exception as e:
            logger.error(f"Error creating exercise definition: {str(e)}")
            return await self.handle_error("create_exercise_definition", e)
    
    async def get_exercise_definition_by_id(self, definition_id: str) -> Dict[str, Any]:
        """
        Get an exercise definition by ID
        """
        try:
            logger.info(f"Getting exercise definition: {definition_id}")
            
            result = await self.supabase.db.table("exercise_definitions") \
                .select("*") \
                .eq("id", definition_id) \
                .execute()
                
            if result.error:
                raise Exception(f"Failed to fetch exercise definition: {result.error.message}")
                
            if not result.data or len(result.data) == 0:
                raise Exception(f"Exercise definition not found: {definition_id}")
                
            definition = result.data[0]
            
            logger.info(f"Retrieved exercise definition: {definition.get('standard_name')}")
            return definition
            
        except Exception as e:
            logger.error(f"Error getting exercise definition: {str(e)}")
            return await self.handle_error("get_exercise_definition_by_id", e)