import React, { useState } from "react";
import { YStack, Text, Input, Button, TextArea } from "tamagui";
import { useUserSessionStore } from "@/stores/userSessionStore";
import { useWorkoutStore } from "@/stores/workout/WorkoutStore"; // ADD THIS IMPORT

interface WorkoutSummarySlideProps {
  onContinue: () => void;
  showContinueButton?: boolean;
}

export function WorkoutSummarySlide({
  onContinue,
  showContinueButton = true,
}: WorkoutSummarySlideProps) {
  const { currentWorkout, updateCurrentWorkout } = useUserSessionStore();
  const { updateWorkout } = useWorkoutStore(); // ADD THIS

  const [workoutName, setWorkoutName] = useState(currentWorkout?.name || "");
  const [workoutNotes, setWorkoutNotes] = useState(() => {
    // Pre-populate with exercise headings if no existing notes
    if (currentWorkout?.notes) {
      return currentWorkout.notes;
    }

    return (
      currentWorkout?.workout_exercises
        ?.map((exercise) => `${exercise.name}:\n\n`)
        .join("\n") || ""
    );
  });

  const handleNameChange = (name: string) => {
    setWorkoutName(name);
    if (currentWorkout) {
      updateCurrentWorkout({
        ...currentWorkout,
        name,
        updated_at: new Date().toISOString(),
      });
    }
  };

  const handleContinue = async () => {
    console.log("=== SUMMARY SLIDE CONTINUE ===");
    console.log("Workout name:", workoutName);
    console.log("Workout notes:", workoutNotes);
    console.log("Workout notes length:", workoutNotes.length);

    if (currentWorkout) {
      const updatedWorkout = {
        ...currentWorkout,
        name: workoutName,
        notes: workoutNotes,
        updated_at: new Date().toISOString(),
      };

      console.log("About to update workout with:", {
        id: updatedWorkout.id,
        name: updatedWorkout.name,
        notes: updatedWorkout.notes,
        notesLength: updatedWorkout.notes?.length,
      });

      updateCurrentWorkout(updatedWorkout);

      // CHECK FOR REAL CHANGES
      const hasNameChanged = workoutName !== currentWorkout.name;

      // For notes: compare against both existing notes AND the auto-generated template
      const originalNotes = currentWorkout.notes || "";
      const autoGeneratedNotes =
        currentWorkout.workout_exercises
          ?.map((exercise) => `${exercise.name}:\n\n`)
          .join("\n") || "";

      // Notes changed if they're different from BOTH original and auto-generated
      const hasNotesChanged =
        workoutNotes !== originalNotes && workoutNotes !== autoGeneratedNotes;

      console.log("Change detection:", {
        hasNameChanged,
        hasNotesChanged,
        originalNotes: originalNotes.length,
        currentNotes: workoutNotes.length,
        autoGeneratedNotes: autoGeneratedNotes.length,
      });

      if (hasNameChanged || hasNotesChanged) {
        console.log("Real changes detected, updating database...");
        try {
          await updateWorkout(updatedWorkout.id, updatedWorkout);
          console.log("Workout successfully saved to database");
        } catch (error) {
          console.error("Failed to save workout:", error);
          // Could show a toast error here if needed
        }
      } else {
        console.log(
          "No real changes detected (only prefilled content), skipping database update"
        );
      }
    }

    onContinue();
  };

  return (
    <YStack gap="$4" paddingBottom="$4">
      <Text fontSize="$6" fontWeight="bold">
        Workout Complete!
      </Text>

      <Input
        value={workoutName}
        onChangeText={handleNameChange}
        placeholder={currentWorkout?.name || "Name your workout..."}
        placeholderTextColor="$textMuted"
        size="$4"
      />

      <YStack gap="$2">
        <Text fontSize="$5" fontWeight="600">
          Notes
        </Text>

        <TextArea
          value={workoutNotes}
          onChangeText={setWorkoutNotes}
          placeholder="Add notes for your workout..."
          minHeight={300}
          backgroundColor="$background"
        />
      </YStack>

      <Button size="$4" backgroundColor="$primary" onPress={handleContinue}>
        Continue to Coach
      </Button>
    </YStack>
  );
}
