import React, { useState } from "react";
import { YStack, Text, Input, Button, TextArea, XStack } from "tamagui";
import { useUserSessionStore } from "@/stores/userSessionStore";
import { useWorkoutStore } from "@/stores/workout/WorkoutStore";
import ImagePickerButton from "../atoms/buttons/ImagePickerButton";
import WorkoutImage from "../molecules/WorkoutImage";
import { imageService } from "@/services/api/imageService";
import { CompleteWorkout } from "@/types/workout";

interface WorkoutSummarySlideProps {
  onContinue: () => void;
  showContinueButton?: boolean;
}

export function WorkoutSummarySlide({
  onContinue,
  showContinueButton = true,
}: WorkoutSummarySlideProps) {
  const {
    currentWorkout,
    updateCurrentWorkout,
    pendingImageId,
    setPendingImage,
    selectedTemplate,
  } = useUserSessionStore();
  const { updateWorkout } = useWorkoutStore();

  const [workoutName, setWorkoutName] = useState("");
  const [showNameError, setShowNameError] = useState(false);
  const [workoutNotes, setWorkoutNotes] = useState(() => {
    console.log("=== WORKOUT SUMMARY DEBUG ===");
    console.log("currentWorkout:", currentWorkout);
    console.log("workout_exercises:", currentWorkout?.workout_exercises);
    console.log(
      "Type of workout_exercises:",
      typeof currentWorkout?.workout_exercises
    );

    if (currentWorkout?.notes) {
      return currentWorkout.notes;
    }

    const exercises = currentWorkout?.workout_exercises || [];
    console.log("Using exercises fallback:", exercises);

    return (
      exercises.map((exercise) => `${exercise.name}:\n\n`).join("\n") || ""
    );
  });

  const handleNameChange = (name: string) => {
    setWorkoutName(name);
  };

  const isNameValid = workoutName.trim().length > 0;

  const handleImageUploaded = (imageId: string) => {
    console.log(`[WorkoutSummary] Image uploaded with ID: ${imageId}`);
    setPendingImage(imageId); // Store in session for immediate display
  };

  const handleImageError = (error: string) => {
    console.error(`[WorkoutSummary] Image upload error: ${error}`);
  };

  const handleContinue = async () => {
    // Validate workout name first
    if (!workoutName.trim()) {
      setShowNameError(true);
      return; // Don't continue
    }
    setShowNameError(false);

    console.log("=== SUMMARY SLIDE CONTINUE ===");
    console.log("Workout name:", workoutName);
    console.log("Workout notes:", workoutNotes);
    console.log("Pending image ID:", pendingImageId);

    if (currentWorkout) {
      try {
        if (!currentWorkout.id || currentWorkout.id.startsWith("temp-")) {
          console.error(
            "❌ Cannot update workout: Invalid ID",
            currentWorkout.id
          );
          return;
        }

        console.log("✅ Updating workout with valid ID:", currentWorkout.id);

        console.log("=== BEFORE UPDATES ===");
        console.log(
          "currentWorkout.workout_exercises length:",
          currentWorkout?.workout_exercises?.length
        );
        console.log(
          "currentWorkout.workout_exercises:",
          currentWorkout?.workout_exercises
        );

        // Check for real changes
        const hasNameChanged = workoutName !== currentWorkout.name;
        const originalNotes = currentWorkout.notes || "";
        const autoGeneratedNotes =
          (currentWorkout.workout_exercises || [])
            .map((exercise) => `${exercise.name}:\n\n`)
            .join("\n") || "";
        const hasNotesChanged =
          workoutNotes !== originalNotes && workoutNotes !== autoGeneratedNotes;
        const hasImageChanged =
          pendingImageId !== (currentWorkout.image_id || null);

        console.log("=== CHANGE DETECTION ===");
        console.log("hasNameChanged:", hasNameChanged);
        console.log("hasNotesChanged:", hasNotesChanged);
        console.log("hasImageChanged:", hasImageChanged);

        // 🔥 COLLECT ALL UPDATES INTO SINGLE CALL
        const updates: Partial<CompleteWorkout> = {};
        let needsUpdate = false;

        if (hasNameChanged || hasNotesChanged) {
          updates.name = workoutName;
          updates.notes = workoutNotes;
          needsUpdate = true;
        }

        if (hasImageChanged && pendingImageId) {
          updates.image_id = pendingImageId;
          needsUpdate = true;
        }

        // 🔥 SINGLE API CALL FOR ALL METADATA
        if (needsUpdate) {
          console.log("=== UPDATING METADATA ===");
          console.log("About to call updateWorkout with updates:", updates);

          const apiUpdatedWorkout = await updateWorkout(
            currentWorkout.id,
            updates
          );

          console.log("=== AFTER API updateWorkout ===");
          console.log("API response:", apiUpdatedWorkout);

          updateCurrentWorkout(apiUpdatedWorkout);
          console.log("Workout metadata updated in session store");

          // Handle image commit if image was updated
          if (hasImageChanged && pendingImageId) {
            console.log("=== COMMITTING IMAGE ===");
            const commitResult = await imageService.commitImage(pendingImageId);
            if (!commitResult.success) {
              throw new Error(commitResult.error || "Failed to commit image");
            }
            setPendingImage(null);
            console.log("Image committed successfully");
          }
        }

        if (needsUpdate) {
          console.log("=== REFRESHING TEMPLATES ===");
          const { fetchTemplates } = useWorkoutStore.getState();
          await fetchTemplates();
          console.log("Templates refreshed");
        } else {
          console.log("No real changes detected, skipping database updates");
        }

        console.log("=== FINAL STATE CHECK ===");
        const finalState = useUserSessionStore.getState().currentWorkout;
        console.log(
          "Final workout_exercises:",
          finalState?.workout_exercises?.length
        );
      } catch (error) {
        console.error("Failed to save workout:", error);
        console.log("=== ERROR STATE CHECK ===");
        const errorState = useUserSessionStore.getState().currentWorkout;
        console.log(
          "Workout_exercises after error:",
          errorState?.workout_exercises?.length
        );
      }
    }
    onContinue();
  };

  return (
    <YStack gap="$4" paddingBottom="$4">
      <Text fontSize="$4" fontWeight="bold">
        Workout Complete!
      </Text>

      <YStack gap="$2">
        <Input
          value={workoutName}
          onChangeText={handleNameChange}
          placeholder={selectedTemplate?.name || "Name your workout..."}
          placeholderTextColor="$textMuted"
          size="$4"
          borderColor={showNameError ? "$red9" : "$borderColor"} // ✅ Visual error indication
        />
        {showNameError && (
          <Text color="$red9" fontSize="$2">
            Please enter a workout name to continue
          </Text>
        )}
      </YStack>

      <YStack gap="$2">
        <Text fontSize="$4" fontWeight="600">
          Add a Photo
        </Text>

        {pendingImageId || currentWorkout?.image_id ? (
          <YStack alignItems="center" gap="$2">
            <WorkoutImage width={300} height={240} />
            <ImagePickerButton
              label="Change Photo"
              icon="camera"
              size="lg"
              onImageUploaded={handleImageUploaded}
              onError={handleImageError}
            />
          </YStack>
        ) : (
          <XStack justifyContent="center">
            <ImagePickerButton
              label="Add Photo"
              icon="camera"
              size="md"
              onImageUploaded={handleImageUploaded}
              onError={handleImageError}
            />
          </XStack>
        )}
      </YStack>

      <YStack gap="$2">
        <Text fontSize="$4" fontWeight="600">
          Notes
        </Text>
        <TextArea
          value={workoutNotes}
          onChangeText={setWorkoutNotes}
          placeholder="Add notes for your workout..."
          minHeight={300}
          backgroundColor="$background"
        />
      </YStack>

      <Button
        size="$4"
        backgroundColor={isNameValid ? "$primary" : "$gray6"}
        onPress={handleContinue}
        disabled={!isNameValid}
        opacity={isNameValid ? 1 : 0.6}
      >
        Continue to Coach
      </Button>
    </YStack>
  );
}
