import React, { useState, useEffect } from "react";
import { YStack, Text, Input, Button, TextArea, XStack } from "tamagui";
import { useUserSessionStore } from "@/stores/userSessionStore";
import { useWorkoutStore } from "@/stores/workout/WorkoutStore";
import ImagePickerButton from "../atoms/buttons/ImagePickerButton";
import { imageService } from "@/services/api/imageService";
import { Image } from "expo-image";

interface WorkoutSummarySlideProps {
  onContinue: () => void;
  showContinueButton?: boolean;
}

export function WorkoutSummarySlide({
  onContinue,
  showContinueButton = true,
}: WorkoutSummarySlideProps) {
  const { currentWorkout, updateCurrentWorkout } = useUserSessionStore();
  const { updateWorkout, updateWorkoutImage } = useWorkoutStore();

  const [workoutName, setWorkoutName] = useState(currentWorkout?.name || "");
  const [showNameError, setShowNameError] = useState(false);
  const [workoutNotes, setWorkoutNotes] = useState(() => {
    console.log("=== WORKOUT SUMMARY DEBUG ===");
    console.log("currentWorkout:", currentWorkout);
    console.log("workout_exercises:", currentWorkout?.workout_exercises);
    console.log(
      "Type of workout_exercises:",
      typeof currentWorkout?.workout_exercises
    );

    if (currentWorkout?.notes) {
      return currentWorkout.notes;
    }

    // Safe fallback with logging
    const exercises = currentWorkout?.workout_exercises || [];
    console.log("Using exercises fallback:", exercises);

    return (
      exercises.map((exercise) => `${exercise.name}:\n\n`).join("\n") || ""
    );
  });
  // Changed: Now track imageId instead of imagePath
  const [currentImageId, setCurrentImageId] = useState<string | null>(
    currentWorkout?.image_id || null
  );

  // For displaying the image, we need the URL
  const [currentImageUrl, setCurrentImageUrl] = useState<string | null>(null);

  // Load image URL when component mounts or imageId changes
  useEffect(() => {
    const loadImageUrl = async () => {
      if (currentImageId) {
        try {
          const urlResponse = await imageService.getImageUrl(currentImageId);
          if (urlResponse.success && urlResponse.url) {
            setCurrentImageUrl(urlResponse.url);
          }
        } catch (error) {
          console.error("[WorkoutSummary] Error loading image URL:", error);
        }
      } else if (currentWorkout?.image_id) {
        // Fallback for existing workouts with image_path
        setCurrentImageUrl(imageService.getPublicUrl(currentWorkout.image_id));
      } else {
        setCurrentImageUrl(null);
      }
    };

    loadImageUrl();
  }, [currentImageId, currentWorkout?.image_id]);

  const handleNameChange = (name: string) => {
    setWorkoutName(name);
    if (currentWorkout) {
      updateCurrentWorkout({
        ...currentWorkout,
        name,
        updated_at: new Date().toISOString(),
      });
    }
  };

  // Changed: Now handles imageId instead of imagePath
  const handleImageUploaded = (imageId: string) => {
    console.log(`[WorkoutSummary] Image uploaded with ID: ${imageId}`);
    setCurrentImageId(imageId);
    // Note: We don't update the workout immediately - just store the imageId locally
  };

  const handleImageError = (error: string) => {
    console.error(`[WorkoutSummary] Image upload error: ${error}`);
  };

  const handleContinue = async () => {
    // Validate workout name first
    if (!workoutName.trim()) {
      setShowNameError(true);
      return; // Don't continue
    }
    setShowNameError(false);

    console.log("=== SUMMARY SLIDE CONTINUE ===");
    console.log("Workout name:", workoutName);
    console.log("Workout notes:", workoutNotes);
    console.log("Workout image ID:", currentImageId);

    if (currentWorkout) {
      try {
        console.log("=== BEFORE UPDATES ===");
        console.log(
          "currentWorkout.workout_exercises length:",
          currentWorkout?.workout_exercises?.length
        );
        console.log(
          "currentWorkout.workout_exercises:",
          currentWorkout?.workout_exercises
        );

        // Check for real changes
        const hasNameChanged = workoutName !== currentWorkout.name;
        const originalNotes = currentWorkout.notes || "";
        const autoGeneratedNotes =
          (currentWorkout.workout_exercises || [])
            .map((exercise) => `${exercise.name}:\n\n`)
            .join("\n") || "";
        const hasNotesChanged =
          workoutNotes !== originalNotes && workoutNotes !== autoGeneratedNotes;
        const hasImageChanged =
          currentImageId !== (currentWorkout.image_id || null);

        console.log("=== CHANGE DETECTION ===");
        console.log("hasNameChanged:", hasNameChanged);
        console.log("hasNotesChanged:", hasNotesChanged);
        console.log("hasImageChanged:", hasImageChanged);

        // Update workout data (name/notes) if changed
        if (hasNameChanged || hasNotesChanged) {
          console.log("=== UPDATING METADATA ===");
          const updatedWorkout = {
            ...currentWorkout,
            name: workoutName,
            notes: workoutNotes,
            updated_at: new Date().toISOString(),
          };

          console.log(
            "About to call updateCurrentWorkout with workout_exercises:",
            updatedWorkout.workout_exercises?.length
          );
          updateCurrentWorkout(updatedWorkout);

          console.log("=== AFTER updateCurrentWorkout ===");
          const stateAfterUpdate =
            useUserSessionStore.getState().currentWorkout;
          console.log(
            "Store state workout_exercises:",
            stateAfterUpdate?.workout_exercises?.length
          );

          console.log("About to call API updateWorkout");
          await updateWorkout(updatedWorkout.id, updatedWorkout);

          console.log("=== AFTER API updateWorkout ===");
          const stateAfterAPI = useUserSessionStore.getState().currentWorkout;
          console.log(
            "Store state after API:",
            stateAfterAPI?.workout_exercises?.length
          );
          console.log("Workout metadata updated");
        }

        // Handle image separately if there's a new image
        if (hasImageChanged && currentImageId) {
          console.log("=== UPDATING IMAGE ===");
          console.log(
            "Store state before image update:",
            useUserSessionStore.getState().currentWorkout?.workout_exercises
              ?.length
          );

          console.log("Committing image and updating workout...");
          await updateWorkoutImage(currentWorkout.id, currentImageId);

          console.log("=== AFTER updateWorkoutImage ===");
          const stateAfterImage = useUserSessionStore.getState().currentWorkout;
          console.log(
            "Store state after image update:",
            stateAfterImage?.workout_exercises?.length
          );
          console.log("Image committed and workout updated");
        }

        if (hasNameChanged || hasNotesChanged || hasImageChanged) {
          console.log("=== REFRESHING TEMPLATES ===");
          const { fetchTemplates } = useWorkoutStore.getState();
          await fetchTemplates();

          console.log("=== AFTER fetchTemplates ===");
          const stateAfterTemplates =
            useUserSessionStore.getState().currentWorkout;
          console.log(
            "Store state after templates:",
            stateAfterTemplates?.workout_exercises?.length
          );
          console.log("Templates refreshed");
        } else {
          console.log("No real changes detected, skipping database updates");
        }

        console.log("=== FINAL STATE CHECK ===");
        const finalState = useUserSessionStore.getState().currentWorkout;
        console.log(
          "Final workout_exercises:",
          finalState?.workout_exercises?.length
        );
      } catch (error) {
        console.error("Failed to save workout:", error);
        console.log("=== ERROR STATE CHECK ===");
        const errorState = useUserSessionStore.getState().currentWorkout;
        console.log(
          "Workout_exercises after error:",
          errorState?.workout_exercises?.length
        );
      }
    }
    onContinue();
  };
  return (
    <YStack gap="$4" paddingBottom="$4">
      <Text fontSize="$6" fontWeight="bold">
        Workout Complete!
      </Text>

      <Input
        value={workoutName}
        onChangeText={handleNameChange}
        placeholder="Name your workout..."
        placeholderTextColor="$textMuted"
        size="$4"
      />

      <YStack gap="$2">
        <Text fontSize="$5" fontWeight="600">
          Add a Photo
        </Text>

        {currentImageUrl ? (
          <YStack alignItems="center" gap="$2">
            <Image
              source={{ uri: currentImageUrl }}
              style={{ width: 200, height: 150, borderRadius: 8 }}
              contentFit="cover"
            />
            <ImagePickerButton
              label="Change Photo"
              icon="camera"
              size="sm"
              onImageUploaded={handleImageUploaded}
              onError={handleImageError}
            />
          </YStack>
        ) : (
          <XStack justifyContent="center">
            <ImagePickerButton
              label="Add Photo"
              icon="camera"
              size="md"
              onImageUploaded={handleImageUploaded}
              onError={handleImageError}
            />
          </XStack>
        )}
      </YStack>

      <YStack gap="$2">
        <Text fontSize="$5" fontWeight="600">
          Notes
        </Text>
        <TextArea
          value={workoutNotes}
          onChangeText={setWorkoutNotes}
          placeholder="Add notes for your workout..."
          minHeight={300}
          backgroundColor="$background"
        />
      </YStack>

      <Button size="$4" backgroundColor="$primary" onPress={handleContinue}>
        Continue to Coach
      </Button>
    </YStack>
  );
}
